name: init_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/CSAADZIDI/init_dart

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^1.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
